version: '2'

services:
  traefik:
    image: traefik:2.4
    command:
      - "--pilot.dashboard=false"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
  api:
    image: shopware/testenv-platform
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${BASE_HOST}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
  mail:
    image: ghcr.io/shyim/shopware-docker/mailhog:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.${BASE_HOST}`)"
      - "traefik.http.routers.mail.entrypoints=web"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"
