version: '2'

services:
  traefik:
    image: traefik:2.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/conf.d:/traefik.conf.d/
    ports:
      - "80:80"
      - "443:443"
  api:
    image: shopware/testenv-platform
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${BASE_HOST}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
