name: CI
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-20.04
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
    - uses: actions/checkout@v2

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - id: generate-jobs
      name: Generate Jobs
      run: |
        cd images/6
        deno run --allow-net build.ts
        strategy="$(deno run --allow-net build.ts)"
        echo $strategy
        echo "::set-output name=strategy::$strategy"

  build:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login into Docker Registery
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "shyim" --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}
