name: Build Manager Image

on:
  workflow_dispatch:  
  push:
    paths: 
      - go.mod
      - go.sum
      - handler/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/shopwarelabs/testenv/manage
          platforms: linux/amd64
          push: true
          provenance: false
