name: Build Shopware

on:
  workflow_dispatch:
  push:
    paths:
      - images/6/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get latest version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/shopware/platform/releases/latest | jq -r .tag_name | sed 's/^.//')
          TAG=$(echo $VERSION | tr . ' ' | awk '{print $1 "." $2 "." $3}')

          echo "version=$VERSION" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_ENV

      - uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/shopwarelabs/testenv:${{ env.tag }}
          build-args: |
            SHOPWARE_VERSION=${{ env.version }}
          context: images/6
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
