name: Build Shopware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: actions/checkout@v2
        
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Image
        run: docker build -t ghcr.io/shopwarelabs/testenv:6.5.2 --build-arg SHOPWARE_VERSION=6.5.2.1 images/6
        
      - name: Push Image
        run: docker push ghcr.io/shopwarelabs/testenv:6.5.2
