name: Build Shopware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: actions/checkout@v2
        
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/shopware/platform/releases/latest | jq -r .tag_name | sed 's/^.//')
          TAG=$(echo $VERSION | tr . ' ' | awk '{print $1 "." $2 "." $3}')

          echo "version=$VERSION" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_ENV
          
      - name: Build Image
        run: docker build -t ghcr.io/shopwarelabs/testenv:${{ env.tag }} --build-arg SHOPWARE_VERSION=${{ env.version }} images/6
        
      - name: Push Image
        run: docker push ghcr.io/shopwarelabs/testenv:${{ env.tag }}
